Catalog view updates
usnistgov/oscal-xslt pull request #4
Opened 2023-04-11 20:54 UTC by wendellpiez

This includes several improvements in XSLT for HTML and FO-based PDF production, making them more robust, more featureful and more general.

Includes scripts and a `pom.xml` file for invoking the production pipeline in Maven.

When these are tested and documented this should be ready.

2023-04-17 13:51 UTC, aj-stein-nist approved these changes
Minor non-blocking feedback, but nice work. Thanks.

2023-04-17 14:52 UTC, wendellpiez commented on publish/nist-emulation/oscal_sp800-53-emulator_fo.xsl
>                <dc:description>  XOXOXOXOX </dc:description>-->
Actually this is probably the one comment I would leave in ... I can add explanation why.

2023-04-17 16:06 UTC, wendellpiez commented on publish/nist-emulation/oscal_sp800-53-emulator_fo.xsl
>                <dc:description>  XOXOXOXOX </dc:description>-->
See https://github.com/usnistgov/oscal-xslt/pull/4/commits/53d7aa0b4917571f2608a1e419b1dfb9515179e9 for some fix up.

2023-04-18 18:13 UTC, aj-stein-nist commented
@Arminta-Jenkins-NIST and @nikitawootten-nist, I would like if you can review this before the end of Sprint 67. Please pull down the code and [the README documentation here](https://github.com/usnistgov/oscal-xslt/blob/c6e6e0265a33a2698dbef8cc0c3a466d188f27ff/publish/readme.md). Thanks!

2023-04-22 05:24 UTC, aj-stein-nist commented
Not completely related so I put it in the OSCAL DKB wiki as an entry, but I added information about how to set up Oxygen transformations in the style I would if you will not exclusively rely on the Maven shell script.

https://github.com/usnistgov/OSCAL/wiki/Developer-Knowledge-Base/5810ad9a2d965fc526995d53ccb91ac129958b69

2023-04-24 19:54 UTC, nikitawootten-nist requested changes
B: Please mark the scripts in `publish/` as executable by running:

```bash
chmod +x publish/*.sh
```

2023-04-24 20:38 UTC, nikitawootten-nist commented
Hi Wendell, I'm also having trouble running the PDF generation script:

```bash
 ➜ ./mvn-make-catalog-pdf.sh basic-catalog.xml result.pdf
[INFO] Scanning for projects...
[INFO]
[INFO] -------< gov.nist.secauto.oscal.tools.core:oscal-xml-formatting >-------
[INFO] Building oscal-xml-formatting 1.0.0
[INFO]   from pom.xml
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- exec:3.1.0:java (default-cli) @ oscal-xml-formatting ---
Apr 24, 2023 4:02:09 PM org.apache.fop.apps.FOUserAgent processEvent
INFO: Rendered page #1.
Apr 24, 2023 4:02:09 PM org.apache.fop.apps.FOUserAgent processEvent
WARNING: The contents of fo:region-after on page i exceed the available area in the block-progression direction by 4800 millipoints. (See position 1:4091)
Apr 24, 2023 4:02:09 PM org.apache.fop.apps.FOUserAgent processEvent
WARNING: The following feature isn't implemented by Apache FOP, yet: table-layout="auto" (on fo:table) (See position 1:8458)
Error on line 1 column 10474 of basic-catalog.xml:
  SXCH0003  org.apache.fop.fo.ValidationException: "fo:page-sequence" is not a valid child
  of "fo:block"! (See position 1:10474). Caused by org.apache.fop.fo.ValidationException:
  file:/Users/naw2/Documents/repos/oscal/oscal-xslt/publish/basic-catalog.xml:1:10474:
  "fo:page-sequence" is not a valid child of "fo:block"! (See position 1:10474)
[com.xmlcalabash.drivers.Main.main()] ERROR com.xmlcalabash.util.DefaultXProcMessageListener - render-oscal-catalog.xpl:52:67:Failed to process FO document with FOP
[com.xmlcalabash.drivers.Main.main()] ERROR com.xmlcalabash.util.DefaultXProcMessageListener -     cause: file:/Users/naw2/Documents/repos/oscal/oscal-xslt/publish/basic-catalog.xml:1:10474:err:SXCH0003:org.apache.fop.fo.ValidationException: "fo:page-sequence" is not a valid child of "fo:block"! (See position 1:10474)
[com.xmlcalabash.drivers.Main.main()] ERROR com.xmlcalabash.drivers.Main - Failed to process FO document with FOP
[com.xmlcalabash.drivers.Main.main()] ERROR com.xmlcalabash.drivers.Main - Underlying exception: org.apache.fop.fo.ValidationException: "fo:page-sequence" is not a valid child of "fo:block"! (See position 1:10474)
```

2023-05-01 20:20 UTC, wendellpiez commented
@nikitawootten-nist @Arminta-Jenkins-NIST feel free to try again thanks!

(The `basic-catalog.xml` isn't the prettiest thing ever but at least it should run now.)

2023-05-01 20:27 UTC, nikitawootten-nist commented
The new update does fix the issue triggered by generating a PDF on a basic catalog!

2023-05-01 20:33 UTC, nikitawootten-nist approved these changes

2023-05-02 17:47 UTC, nikitawootten-nist commented
@wendellpiez is this ready to merge now?

2023-05-03 15:50 UTC, merged